### PR TITLE
setup CIs

### PR DESCRIPTION
**Pull request by agramfort**

### CODE REVIEW

**Comment by anujanegi** [comment]
@agramfort I added the missing files, only 6 fails now (coming from the stringent test cases)

**Comment by agramfort** [comment]
thx @anujanegi can you push the fixes here? 🙏

**Comment by anujanegi** [comment]
I already did. Check the latest gh-action run. @agramfort

**Comment by agramfort** [comment]
great

could you open a PR just to make the CIs green so we build without breaking
previous stuff? thx

**Pull request merged**
