### PR TITLE
Improved test speed

### PR DESCRIPTION
**Pull request by AliHashemi-ai**
working with @agramfort

### CODE REVIEW

**Comment by AliHashemi-ai** [comment]
Hi @agramfort , I revised some conditions in the code to pass all the test cases. Please take a look. Just one thing to consider is the way that I calculate the matrices in here: https://github.com/braindatalab/BSI-Zoo/blob/improved-test-speed/bsi_zoo/estimators.py#L390 

Do you have any idea to make it faster by changing its implementation? 

As we discussed, I will import mixed_norm_solver function from MNE to the repo later today to extend the methods for n_orient = 3. 

(I am on vacation this week but I will try to contribute to the repo as much as I can since I am a little bit free now after my defense)

**Comment by agramfort** [comment]
@AliHashemi-ai I pushed a commit to speed up these few lines

**Comment by agramfort** [comment]
@AliHashemi-ai this is now green. Shall we merge and continue in the next PR?

**Comment by AliHashemi-ai** [comment]
> @AliHashemi-ai this is now green. Shall we merge and continue in the next PR?

Hi @agramfort  Thanks for your revision. I saw your speed up modification, but I wonder why you replaced the wmat fucntion here https://github.com/braindatalab/BSI-Zoo/blob/improved-test-speed/bsi_zoo/estimators.py#L393
Right now that we are working with n_orient = 1 it does not make a difference, but it will certainly affect the method when we want to run the methods for n_orient = 3 as you can see in https://github.com/braindatalab/BSI-Zoo/blob/improved-test-speed/bsi_zoo/estimators.py#L383

**Comment by AliHashemi-ai** [comment]
> > @AliHashemi-ai this is now green. Shall we merge and continue in the next PR?
> 
> Hi @agramfort Thanks for your revision. I saw your speed up modification, but I wonder why you replaced the wmat fucntion here https://github.com/braindatalab/BSI-Zoo/blob/improved-test-speed/bsi_zoo/estimators.py#L393 Right now that we are working with n_orient = 1 it does not make a difference, but it will certainly affect the method when we want to run the methods for n_orient = 3 as you can see in https://github.com/braindatalab/BSI-Zoo/blob/improved-test-speed/bsi_zoo/estimators.py#L383

I agree to merge this PR to master after we confirmed on this point

**Comment by agramfort** [comment]
Indeed I broke something. Tests should have spotted it. I will fix asap and we merge afterwards. Good catch !

**Comment by agramfort** [comment]
pushed a fix

**Comment by AliHashemi-ai** [comment]
> pushed a fix

Hi @agramfort , thanks but I could not find your pushed commit here ? have you already pushed to fix to this branch?

**Comment by agramfort** [comment]
fixed now. My push had been rejected as you had pushed in the mean time

**Comment by AliHashemi-ai** [comment]
> fixed now. My push had been rejected as you had pushed in the mean time
> […](#)
> Message ID: ***@***.***>

Thank you @agramfort. Now it's looking fine. shall we merge it with master and move forward with n_orient = 3?

**Comment by agramfort** [comment]
let's move on to n_orient= 3

thanks @AliHashemi-ai

**Pull request merged**
