### PR TITLE
adding eloreta based on Stefan's MATLAB code

### PR DESCRIPTION
**Pull request by AliHashemi-ai**
@agramfort @stefanhaufe @anujanegi
could you please check this Python code for eLORETA which I basically translated from Stefan's MATLAB's code?

### CODE REVIEW

**Comment by agramfort** [comment]
@AliHashemi-ai I spent 2 hours to prepare a function you could use based on the mne code. did you compare this implementation with mine?

**Comment by anujanegi** [comment]
sorry i've been sick this week, but i can takeover eLORETA. I already got started a bit

**Comment by AliHashemi-ai** [comment]
> @AliHashemi-ai I spent 2 hours to prepare a function you could use based on the mne code. did you compare this implementation with mine?

@agramfort did you ping me or make a pull request since I have not received your message in github?

**Comment by anujanegi** [comment]
@AliHashemi-ai https://github.com/braindatalab/BSI-Zoo/issues/54

**Comment by AliHashemi-ai** [comment]
> @AliHashemi-ai #54

@agramfort there are a couple of differences, which I will discuss in our meeting. The part based on Guido Nolte's code is similar.

**Pull request closed without merging**
